### ISSUE TITLE
Cython?

### ISSUE THREAD

**Issue by nclowell** [OARS-SAFS/resources#17]
Does anyone use Cython and if so can you field a few questions?

I have a Python script (``GRs.py``) I'm trying to speed up. I changed the extension to ``.pyx`` to make it a Cython file, and call it from another Python script using

```
import pyximport
pyximport.install()
import GRs
```

In theory, it will have compiled the ``GRs.pyx`` and run it. However I'm getting an error about zero division, which I never get when running the original script in Python. 

I also notice that the print statements are different where it prints the result of  it as a tuple in Cython, e.g.,

The line in Python is 
```
print(" Rep", rep, datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d %H:%M:%S'))
```

It prints from Python as
```
 Rep 0 2021-04-06 17:43:28

```

It prints from Cython as
```
(' Rep', 0, '2021-04-07 16:00:29')
```

Help??

**Comment by kubu4** [comment]
Could you post links to the scripts for people to review?

**Comment by nclowell** [comment]
Yea sure! Here's the [.pyx file](https://github.com/nclowell/side_projects/blob/main/other/GRs.pxy) and here's the [script](https://github.com/nclowell/side_projects/blob/main/other/testing.py) I used to compile it and call it.

**Comment by kubu4** [comment]
> However I'm getting an error about zero division, which I never get when running the original script in Python.

Also, can you please copy/paste the exact error message when you have the chance?

**Comment by nclowell** [comment]
Yes!

```
$ python testing.py test 1 1
Reading in parameter values
('batch', 'test_1')
Initializing response variable storage objecs and logs
(' Rep', 0, '2021-04-09 15:03:00')
  Initializing starting population
Traceback (most recent call last):
  File "testing.py", line 3, in <module>
    import GRs
  File "GRs.pyx", line 996, in init GRs
ZeroDivisionError: division by zero
```
